/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.controladorLogueo;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.dao.logueoDao;
import modelo.logica.Logica;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author USER
 */
public class Principal extends javax.swing.JFrame {
    Statement mistatement;
    Connection con;
    VistaMenu vm= new VistaMenu();

    private controladorLogueo controlLogueo;
    
    public void setControladorLogueo(controladorLogueo controlLogueo){
        
        this.controlLogueo=controlLogueo;
    }
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        
        initComponents();
        this.setLocationRelativeTo(this);
        rsscalelabel.RSScaleLabel.setScaleLabel(jlLogo, "..\\NuevaInterfaz\\src\\Imagenes\\Logo.png");
        //rsscalelabel.RSScaleLabel.setScaleLabel(lblHerbario, "C:\\Users\\USER\\Desktop\\Neatbeans-2022\\Proyecto-Farmacia\\src\\Imagenes\\herbario.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblHerbario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        cbTipoUsuario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña:");

        txtUsuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        btnIngresar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblHerbario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/herbario (1) (1).png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Farmacias C & K");

        txtClave.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });

        cbTipoUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo", "Empleado General", "Administrador del sistema" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHerbario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTipoUsuario, 0, 193, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnIngresar))
                            .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtClave, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHerbario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btnIngresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(10, 10, 10))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        String usuario= "c##"+txtUsuario.getText();
        System.out.println(usuario);
        String clave = txtClave.getText();
        String tipo= (String) cbTipoUsuario.getSelectedItem();        
        //boolean busqueda=false;
        boolean busqueda = false;

       try {
                if(con!=null && con.isValid(0)){
                    
                    ResultSet listado= controlLogueo.IngresarTF(usuario, clave, tipo);
                    while (listado.next()) {  
                        System.out.println(tipo);
                        busqueda=true;
                        VistaMenu vm=new VistaMenu();
                    controladorLogueo controlLogueoMenu=new controladorLogueo();        
                    vm.setControladorLogueo(controlLogueoMenu);
                    controlLogueoMenu.setVistaMenu(vm);
                    Logica logic=new Logica();
                    controlLogueoMenu.setLogica(logic);
                    vm.setVisible(true);
                    this.dispose();
                    vm.lblUsuario.setText(usuario);
                    vm.lblTipoE.setText(tipo);
                    
                    }
                    

                    
                }
                
                else{
                    busqueda = true;
                    DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                    System.out.println("Conectando con la base de datos..");
                    con= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", usuario, clave);
                    mistatement = con.createStatement();
                    System.out.println("CONEXIÓN EXITOSA");
                    
                    if(con!=null && con.isValid(0)){
                        ResultSet listado= controlLogueo.IngresarTF(usuario, clave, tipo);

                        try{
                        while (listado.next()) {  

                            if(tipo.equals(listado.getString("tip_detalle"))){
                                System.out.println(tipo);
                                busqueda = true;
                                VistaMenu vm = new VistaMenu();
                                controladorLogueo controlLogueoMenu = new controladorLogueo();
                                vm.setControladorLogueo(controlLogueoMenu);
                                controlLogueoMenu.setVistaMenu(vm);
                                Logica logic = new Logica();
                                controlLogueoMenu.setLogica(logic);
                                vm.setVisible(true);
                                this.dispose();
                                vm.lblUsuario.setText(usuario);
                                vm.lblTipoE.setText(tipo);
                                
                                
                            }
                            else{
                            JOptionPane.showMessageDialog(null, "aaaaaaaaaaaaaaaaaaaaaa");  
                            }
                        
                    }
 
                    }
                        catch (SQLException ex){
                               JOptionPane.showMessageDialog(null, "aaaaaaaaaaaaaaaaaaaaaa");  
                        }
                    }
                    
                ///////////////////////////
                    
                //////////////////////////
                    
                }
                /*else{
                    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorretos");
                }*/
                ///////////////////////////////////////////////////////////////
                ///////////////////INICIALIZAR VENTANA MENU////////////////////
                
            } 
            catch (SQLException ex) {
                //Logger.getLogger(logueoDao.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos"); 
               busqueda = false;
               System.out.println("La excepcion raiz es: "+ ex);
               
                
            }
       //System.out.println(VistaMenu.lblUsuario.getText()+"11");
        System.out.println(VistaMenu.lblTipoE.getText()+"-----");
        String tpe="Empleado General";
        if(VistaMenu.lblTipoE.getText().equals(tpe)){
            VistaMenu.btnEliminar.setEnabled(false);
            VistaMenu.btnEmpleados.setEnabled(false);
            VistaMenu.btnTipoE.setEnabled(false);
            VistaMenu.btnProveedor.setEnabled(false);
            VistaMenu.btnAgregarCategoria.setEnabled(false);
            VistaMenu.btnModificarCategoria.setEnabled(false);
            VistaMenu.btnEliminarCategoria.setEnabled(false);
            VistaMenu.btnAgregarPR.setEnabled(false);
            VistaMenu.btnModificarPR.setEnabled(false);
            VistaMenu.btnEliminarPR.setEnabled(false);
            VistaMenu.btnInventario.setEnabled(false);
            
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed
    
    public void  limpiar(){
        txtClave.setText("");
        txtUsuario.setText("");
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cbTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel lblHerbario;
    public static javax.swing.JPasswordField txtClave;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
